apps/courses/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/25 21:47'

from django.urls import path


from . import views

app_name = 'courses'

urlpatterns = [
    path('specialized_courses_list/', views.SpecializedCoursesList.as_view(), name='specialized_courses_list'),
    path('open_courses_list/', views.OpenCoursesList.as_view(), name='open_courses_list'),
    path('course_detail/<int:course_id>/', views.CourseDetail.as_view(), name='course_detail'),

    # 课程学习
    path('course_study/<int:course_id>/', views.CourseStudy.as_view(), name='course_study'),
    # 课程评论
    path('course_comment/<int:course_id>/', views.CourseCommentView.as_view(), name='course_comment'),
    # 添加课程评论
    path('add_course_comment/', views.AddCourseCommentView.as_view(), name='add_course_comment'),
    # 添加课程到用户的学习表
    path('add_course_study',views.AddCourseStudy.as_view(), name='add_course_study'),
    # 课程的章节学习页面
    path('course_study_detail/<int:course_id>/<int:section_id>/', views.CourseStudyDetail.as_view(), name='course_study_detail'),
]

apps/operations/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/25 18:14'

from django.urls import path
from . import views

app_name = 'operations'

urlpatterns = [
    # 用户个人中心
    path('user_center_information/', views.UserCenterInformation.as_view(), name='user_center_information'),

    # 用户学习的课程
    path('user_center_my_courses/', views.UserStudyCourse.as_view(), name='user_center_my_courses'),

    # 用户消息
    path('user_center_messages/', views.UserMessageView.as_view(), name='user_center_messages'),

    # 用户收藏的教师
    path('user_center_fav_teachers/', views.UserCollectedTeacher.as_view(), name='user_center_fav_teachers'),
    # 用户收藏的教师
    path('user_center_fav_courses/', views.UserCollectedCourse.as_view(), name='user_center_fav_courses'),
    # 用户收藏的教师
    path('user_center_fav_organizations/', views.UserCollectedOrganization.as_view(), name='user_center_fav_organizations'),

    # 修改用户头像
    path('reset_head_portrait/', views.ResetUserHeaderPortraitView.as_view(), name='reset_head_portrait'),
    # 修改用户密码
    path('reset_user_password/', views.ResetUserPasswordView.as_view(), name='reset_user_password'),
    # 修改用户信息
    path('reset_user_information/', views.ResetUserInformationView.as_view(), name='reset_user_information'),
    # 修改邮箱是发送的验证码
    path('send_email_verify_record/', views.SendEmailView.as_view(), name='send_email_verify_record'),
    # 修改邮箱
    path('reset_user_email/', views.ResetUserEmailView.as_view(), name='reset_user_email'),

    # 读取用户消息
    path('read_message/', views.ReadMessageView.as_view(), name='read_message'),


]

apps/organizations/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/25 21:47'

from django.urls import path

from . import views

app_name = 'organizations'

urlpatterns = [
    # 课程机构列表
    path('organizations_list/', views.OrganizationsList.as_view(), name='organizations_list'),
    # 课程咨询
    path('add_ask/', views.AddUserAsk.as_view(), name='add_ask'),
    # 机构详情
    path('organization_detail_homepage/<int:org_id>/', views.OrganizationHomePage.as_view(), name='organization_detail_homepage'),
    path('organization_detail_courses/<int:org_id>/', views.OrganizationCoursePage.as_view(), name='organization_detail_courses'),
    path('organization_detail_teachers/<int:org_id>/', views.OrganizationTeacherPage.as_view(), name='organization_detail_teachers'),
    path('organization_detail_description/<int:org_id>/', views.OrganizationDescripthionPage.as_view(), name='organization_detail_description'),
    # 收藏功能
    path('add_collection', views.AddCollection.as_view(), name='add_collection'),


    path('teacher_detail/<int:teacher_id>', views.TeacherInformation.as_view(), name='teacher_detail'),
    path('teachers_list/', views.TeacherList.as_view(), name='teachers_list'),
]

diandian_online/urls.py
# _*_ coding: utf-8 _*_

"""diandian_online URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import xadmin
from django.views.generic import TemplateView

# 静态文件请求的处理
from django.views.static import serve
from diandian_online import settings
from apps.users import views


urlpatterns = [

    # 首页
    path('', views.Index.as_view(), name='index'),
    # xadmin 的后台
    path('xadmin/', xadmin.site.urls),

    # 用户相关的页面
    path('users/', include('users.urls')),
    # 用户操作相关的页面
    path('operations/', include('operations.urls')),
    # 课程页面
    path('courses/', include('courses.urls')),
    # 机构页面
    path('organizations/', include('organizations.urls')),

    # 配置验证码
    path('captcha/', include('captcha.urls')),
    # 配置图片请求
    path('media/<path:path>/', serve, {'document_root': settings.MEDIA_ROOT}),

    # xadmin 第三方的富文本插件
    path('ueditor/',include('DUEditor.urls' )),

    # 配置未上线时的错误页面调试的静态文件路径
    # path('static/<path:path>/', serve, {'document_root': settings.STATIC_ROOT}),
]


# 404 错误页面 （一般是错误的 url 导致的)
handler404 = 'users.views.handler_404_error'
handler500 = 'users.views.handler_500_error'
handler403 = 'users.views.handler_403_error'

extra_apps/DUEditor/urls.py
#coding:utf-8
'''
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import url
else:
    from django.conf.urls.defaults import patterns, url


'''
from django.urls import path
from django.conf.urls import url
from .views import get_ueditor_controller


urlpatterns = [
    path('controller/', get_ueditor_controller),
]

apps/operations/forms.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/3/6 22:24'

import re

from django import forms
from users.models import UserProfiles


class ResetUserHeaderPortraitForm(forms.ModelForm):

    class Meta:
        model = UserProfiles
        fields = ['head_portrait']


class ResetUserPasswordForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=6, max_length=16)
    password2 = forms.CharField(required=True, min_length=6, max_length=16)


class SendEmailForm(forms.Form):
    email = forms.EmailField(required=True)


class ResetUserInformationForm(forms.ModelForm):

    class Meta:
        model = UserProfiles
        fields = ['nick_name', 'birthday', 'gender', 'address', 'mobile']

    def clean_mobile(self):
        """
        验证手机号码是否合法
        """
        mobile = self.cleaned_data['mobile']
        regex = r'^1[3|4|5|7|8]\d{9}$'
        pattern = re.compile(regex)
        if pattern.match(mobile):
            return mobile
        else:
            raise forms.ValidationError(u'无效的手机号码', code='mobile_invalid')

apps/operations/views.py
# _*_ coding: utf-8 _*_

import json
from time import sleep

from django.shortcuts import render, reverse
from django.views.generic import View
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.contrib.auth.hashers import make_password
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

from .models import UserCourse, UserCollection, UserMessage
from courses.models import Course
from organizations.models import CourseOrganization, Teacher
from users.models import UserProfiles, EmailVerifyRecord
from utils.mixin_utils import LoginRequiredMixin
from utils.email_send import send_email_verify_record
from .forms import ResetUserHeaderPortraitForm, ResetUserPasswordForm, SendEmailForm, ResetUserInformationForm


# 定义获取用户收藏的函数
def get_user_collect(user_id, collection_type):
    course_teacher_org = {
        '1': Course,
        '2': CourseOrganization,
        '3': Teacher,
    }
    collection_ids = [collection.collection_id for collection in UserCollection.objects.filter(
        user_id=user_id,
        collection_type=collection_type)]
    collections = course_teacher_org.get(str(collection_type)).objects.filter(pk__in=collection_ids)
    return collections


# 用户个人中心-用户信息
class UserCenterInformation(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        return render(request, 'operations/usercenter-info.html', {
            'user': user,
            'focus': 'user_info',
        })


# 用户学习的课程
class UserStudyCourse(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user.id

        # 获取用户学习的课程信息
        course_ids =[course.course_id for course in  UserCourse.objects.filter(user_id=user)]
        # 使用关键字 __in 来获取列表中的条件
        user_courses = Course.objects.filter(pk__in=course_ids)

        return render(request, 'operations/usercenter-mycourse.html', {
            'user_courses': user_courses,
            'focus': 'user_mycourse',
        })


# 用户消息
class UserMessageView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user

        # 获取用户消息
        user_messages = UserMessage.objects.filter(user=user.id).order_by("-send_time")
        for user_message in user_messages:
            user_message.has_read = True
            user_message.save()


        # 获取页面传回的分页数值，默认为 1（第一页）
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        # 对数据库中所取出的所有对象，进行分页，中间的参数为每页显示的对象个数，设置为 6 个
        p = Paginator(user_messages, 6, request=request)
        # 取出对应页的数据
        user_message_list = p.page(page)

        return render(request, 'operations/usercenter-message.html', {
            'user': user,
            'user_messages': user_message_list,
            'focus': 'user_message',
        })


# 用户收藏的讲师
class UserCollectedTeacher(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user

        collections = get_user_collect(user_id=user, collection_type=3)

        return render(request, 'operations/usercenter-fav-teacher.html', {
            'user': user,
            'focus': 'user_fav',
            'collections': collections,
        })



# 用户收藏的课程
class UserCollectedCourse(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user

        collections = get_user_collect(user_id=user, collection_type=1)

        return render(request, 'operations/usercenter-fav-course.html', {
            'user': user,
            'focus': 'user_fav',
            'collections': collections,
        })


# 用户收藏的讲师
class UserCollectedOrganization(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user

        collections = get_user_collect(user_id=user, collection_type=2)

        return render(request, 'operations/usercenter-fav-org.html', {
            'user': user,
            'focus': 'user_fav',
            'collections': collections,
        })


# 修改用户头像
class ResetUserHeaderPortraitView(LoginRequiredMixin, View):
    def post(self, request):
        # request 对象中有一个 FILES 对象，相应中携带的文件保存在这里
        head_portrait_form = ResetUserHeaderPortraitForm(request.POST, request.FILES, instance=request.user)
        if head_portrait_form.is_valid():
            request.user.save()
            return JsonResponse({'static': 'success'})
        else:
            return JsonResponse({'static': 'fail'})


# 修改用户密码
class ResetUserPasswordView(View):
    def post(self, request):
        password_form = ResetUserPasswordForm(request.POST)
        if password_form.is_valid():
            password1 = request.POST.get('password1', '')
            password2 = request.POST.get('password2', '')
            if password1 != password2:
                return JsonResponse({'status': 'fail', 'msg': u'两次输入的密码不一致'})
            user = request.user
            user.password = make_password(password1)
            user.save()
            return JsonResponse({'status': 'success'})
        else:
            # 这里一定要加上这个参数 safe=False
            # 这样如果传入的不是正常的字典，也可以返回
            # 否则会报错 TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
            # result = json.dumps(password_form.errors)
            # return JsonResponse(result, safe=False)
            # 这里直接使用 JsonResponse 有问题，传入的错误信息，前端无法显示
            return HttpResponse(json.dumps(password_form.errors), content_type='application/json')


# 修改用户邮箱
class SendEmailView(View):
    def get(self, request):
        email_form = SendEmailForm(request.GET)

        if email_form.is_valid():
            # 获取用户填入的邮箱，并进行唯一性验证，如果是已经注册过的邮箱，返回错误信息
            new_email = request.GET.get('email')
            exist_email = UserProfiles.objects.filter(email=new_email)
            if exist_email:
                return JsonResponse({'email': u'该邮箱已被注册'})

            # 发送修改邮箱的邮件验证码
            send_status = send_email_verify_record(new_email, 'reset_email')
            # 验证是否发送成功，如果送失败，重发三次，如果还是失败，删除用户数据，提示用户重新注册

            if not send_status:
                resend_status = False
                for times in range(3):
                    resend_status = send_email_verify_record(new_email, 'reset_email')
                    if resend_status:
                        break
                if not resend_status:
                    return JsonResponse({'status':'fail', 'msg': u'邮件发送失败，请稍后再试'})

            # 邮件发送成功
            return JsonResponse({'status':'success', 'msg': u'邮件发送成功'})

        # 邮件格式验证错误
        return JsonResponse({'status': 'fail', 'msg': u'邮箱格式不合规'})


class ResetUserEmailView(View):
    def post(self, request):
        # 获取前端传回的信息
        email = request.POST.get('email', '')
        code = request.POST.get('code', '')
        # 进入数据库库验证邮件验证码
        email_verify = EmailVerifyRecord.objects.filter(email=email, code=code, send_type='reset_email')
        if email_verify:
            user = request.user
            user.email = email
            user.save()
            return JsonResponse({'status':'success'})
        else:
            return JsonResponse({'status':'fail', 'email': u'验证码错误'})


# 修改用户信息
class ResetUserInformationView(View):
    def post(self, request):
        user_info_form = ResetUserInformationForm(request.POST, instance=request.user)
        if user_info_form.is_valid():
            request.user.save()
            return JsonResponse({'status':'success'})
        else:
            return HttpResponse(json.dumps(user_info_form.errors), content_type='application/json')


# 读取用户消息
class ReadMessageView(View):
    def post(self, request):
        pass

apps/operations/templates/operations/usercenter-fav-course.html
<!DOCTYPE html>
<html>

{% extends 'base_usercenter.html' %}
{% load static %}

<head>

    {% block custom_head_js %}
        <script type="text/javascript">
    $(document).ready(function() {
        $('.jsDeleteFav_course').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            alert(favid)
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: '799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
    });

    $(document).ready(function() {
        $('.jsDeleteFav_teacher').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 3,
                    fav_id: favid,
                    csrfmiddlewaretoken: '799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
    });

    $(document).ready(function() {
        $('.jsDeleteFav_org').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 2,
                    fav_id: favid,
                    csrfmiddlewaretoken: '799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
    });
</script>
        <script type="text/javascript">
        var shareUrl = '',
            shareText = '',
            shareDesc = '',
            shareComment = '';
        $(function () {
            $(".bdsharebuttonbox a").mouseover(function () {
                var type = $(this).attr('data-cmd'),
                    $parent = $(this).parent('.bdsharebuttonbox'),
                    fxurl = $parent.attr('data-url'),
                    fxtext = $parent.attr('data-text'),
                    fxdesc = $parent.attr('data-desc'),
                    fxcomment = $parent.attr('data-comment');
                switch (type){
                    case 'tsina':
                    case 'tqq':
                    case 'renren':
                            shareUrl = fxurl;
                            shareText = fxdesc;
                            shareDesc = '';
                            shareComment = '';
                        break;
                    default :
                            shareUrl = fxurl;
                            shareText = fxtext;
                            shareDesc = fxdesc;
                            shareComment = fxcomment;
                        break;
                }
            });
        });
        function SetShareUrl(cmd, config) {
            if (shareUrl) {
                config.bdUrl = "" + shareUrl;
            }
            if(shareText){
                config.bdText = shareText;
            }
            if(shareDesc){
                config.bdDesc = shareDesc;
            }
            if(shareComment){
                config.bdComment = shareComment;
            }

            return config;
        }
        window._bd_share_config = {
            "common": {
                "onBeforeClick":SetShareUrl,
                "bdPic":"",
                "bdMini":"2",
                "searchPic":"1",
                "bdMiniList":false
            },
            "share": {
                "bdSize":"16"
            }
        };
    with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com../api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
</script>
    {% endblock %}

</head>
<body>


    <!-- 每个网页的面包屑导航，需自定义（按需体现） -->
    {% block custom_breadcrumbs %}
        <section>
            <div class="wp">
                <ul  class="crumbs">
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'operations:user_center_information' %}">个人中心</a>></li>
                    <li>我的收藏</li>
                </ul>
            </div>
        </section>
    {% endblock %}

    <!-- 每个网页的页面主体，需自定义 -->
    {% block custom_body %}
        <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'operations:user_center_fav_organizations' %}">课程机构</a> </li>
                        <li><a href="{% url 'operations:user_center_fav_teachers' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'operations:user_center_fav_courses' %}">课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in collections %}
                            <div class="module1_5 box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.course_image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:course_detail' course.id %}">
                                        <h2>{{ course.course_name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.learen_times }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl">
                                        <a href="{% url 'organizations:organization_detail_homepage' course.course_teacher.organization.id %}"
                                            style="color: #6e6e6e;">
                                            {{ course.course_teacher.organization.organization_name }}
                                        </a>
                                    </span>
                                    <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}


</body>
</html>

apps/operations/templates/operations/usercenter-fav-org.html
<!DOCTYPE html>
<html>

{% extends 'base_usercenter.html' %}
{% load static %}

<head>

    {% block custom_head_js %}
        <script type="text/javascript">
    $(document).ready(function() {
        $('.jsDeleteFav_course').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            alert(favid)
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: '799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
    });

    $(document).ready(function() {
        $('.jsDeleteFav_teacher').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 3,
                    fav_id: favid,
                    csrfmiddlewaretoken: '799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
    });

    $(document).ready(function() {
        $('.jsDeleteFav_org').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 2,
                    fav_id: favid,
                    csrfmiddlewaretoken: '799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
    });
</script>
        <script type="text/javascript">
        var shareUrl = '',
            shareText = '',
            shareDesc = '',
            shareComment = '';
        $(function () {
            $(".bdsharebuttonbox a").mouseover(function () {
                var type = $(this).attr('data-cmd'),
                    $parent = $(this).parent('.bdsharebuttonbox'),
                    fxurl = $parent.attr('data-url'),
                    fxtext = $parent.attr('data-text'),
                    fxdesc = $parent.attr('data-desc'),
                    fxcomment = $parent.attr('data-comment');
                switch (type){
                    case 'tsina':
                    case 'tqq':
                    case 'renren':
                            shareUrl = fxurl;
                            shareText = fxdesc;
                            shareDesc = '';
                            shareComment = '';
                        break;
                    default :
                            shareUrl = fxurl;
                            shareText = fxtext;
                            shareDesc = fxdesc;
                            shareComment = fxcomment;
                        break;
                }
            });
        });
        function SetShareUrl(cmd, config) {
            if (shareUrl) {
                config.bdUrl = "" + shareUrl;
            }
            if(shareText){
                config.bdText = shareText;
            }
            if(shareDesc){
                config.bdDesc = shareDesc;
            }
            if(shareComment){
                config.bdComment = shareComment;
            }

            return config;
        }
        window._bd_share_config = {
            "common": {
                "onBeforeClick":SetShareUrl,
                "bdPic":"",
                "bdMini":"2",
                "searchPic":"1",
                "bdMiniList":false
            },
            "share": {
                "bdSize":"16"
            }
        };
    with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com../api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
</script>
    {% endblock %}

</head>
<body>


    <!-- 每个网页的面包屑导航，需自定义（按需体现） -->
    {% block custom_breadcrumbs %}
        <section>
            <div class="wp">
                <ul  class="crumbs">
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'operations:user_center_information' %}">个人中心</a>></li>
                    <li>我的收藏</li>
                </ul>
            </div>
        </section>
    {% endblock %}

    <!-- 每个网页的页面主体，需自定义 -->
    {% block custom_body %}
        <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'operations:user_center_fav_organizations' %}">课程机构</a> </li>
                        <li><a href="{% url 'operations:user_center_fav_teachers' %}">授课教师 </a></li>
                        <li><a href="{% url 'operations:user_center_fav_courses' %}">课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">

                    {% for org in collections %}
                        <div class="messages butler_list company company-fav-box">
                            <dl class="des fr">
                                <dt>
                                    <a href="{% url 'organizations:organization_detail_homepage' org.id %}">
                                        <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.organization_image }}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <h1>
                                        <a href="{% url 'organizations:organization_detail_homepage' org.id %}">
                                            {{ org.org_name }}
                                        </a>
                                    </h1>
                                    <div class="pic fl" style="width:auto;">
                                        <img src="{% static 'images/authentication.png' %}"/>
                                        <img src="{% static 'images/gold.png' %}"/>
                                    </div>
                                    <span class="c8 clear">{{ org.address }}</span>
                                    <div class="delete jsDeleteFav_org" data-favid="1"></div>
                                </dd>
                            </dl>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    {% endblock %}


</body>
</html>