apps/courses/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/25 21:47'

from django.urls import path


from . import views

app_name = 'courses'

urlpatterns = [
    path('specialized_courses_list/', views.SpecializedCoursesList.as_view(), name='specialized_courses_list'),
    path('open_courses_list/', views.OpenCoursesList.as_view(), name='open_courses_list'),
    path('course_detail/<int:course_id>/', views.CourseDetail.as_view(), name='course_detail'),

    # 课程学习
    path('course_study/<int:course_id>/', views.CourseStudy.as_view(), name='course_study'),
    # 课程评论
    path('course_comment/<int:course_id>/', views.CourseCommentView.as_view(), name='course_comment'),
    # 添加课程评论
    path('add_course_comment/', views.AddCourseCommentView.as_view(), name='add_course_comment'),
    # 添加课程到用户的学习表
    path('add_course_study',views.AddCourseStudy.as_view(), name='add_course_study'),
    # 课程的章节学习页面
    path('course_study_detail/<int:course_id>/<int:section_id>/', views.CourseStudyDetail.as_view(), name='course_study_detail'),
]

apps/organizations/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/25 21:47'

from django.urls import path

from . import views

app_name = 'organizations'

urlpatterns = [
    # 课程机构列表
    path('organizations_list/', views.OrganizationsList.as_view(), name='organizations_list'),
    # 课程咨询
    path('add_ask/', views.AddUserAsk.as_view(), name='add_ask'),
    # 机构详情
    path('organization_detail_homepage/<int:org_id>/', views.OrganizationHomePage.as_view(), name='organization_detail_homepage'),
    path('organization_detail_courses/<int:org_id>/', views.OrganizationCoursePage.as_view(), name='organization_detail_courses'),
    path('organization_detail_teachers/<int:org_id>/', views.OrganizationTeacherPage.as_view(), name='organization_detail_teachers'),
    path('organization_detail_description/<int:org_id>/', views.OrganizationDescripthionPage.as_view(), name='organization_detail_description'),
    # 收藏功能
    path('add_collection', views.AddCollection.as_view(), name='add_collection'),


    path('teacher_detail/<int:teacher_id>', views.TeacherInformation.as_view(), name='teacher_detail'),
    path('teachers_list/', views.TeacherList.as_view(), name='teachers_list'),
]

apps/users/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/20 19:52'

from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    # path('', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('active/<slug:active_code>/', views.ActiveCode.as_view(), name='user_active'),
    path('forget_password/', views.ForgetPassword.as_view(), name='forget_password'),
    path('forget/<slug:user_name>/<slug:forget_password_code>/', views.ForgetPassWordCode.as_view(), name='reset_password_verify'),
    path('reset_password/', views.ResetPassword.as_view(), name='reset_password'),

]

diandian_online/urls.py
# _*_ coding: utf-8 _*_

"""diandian_online URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import xadmin
from django.views.generic import TemplateView

# 静态文件请求的处理
from django.views.static import serve
from diandian_online import settings
from apps.users import views


urlpatterns = [

    # 首页
    path('', views.Index.as_view(), name='index'),
    # xadmin 的后台
    path('xadmin/', xadmin.site.urls),

    # 用户相关的页面
    path('users/', include('users.urls')),
    # 用户操作相关的页面
    path('operations/', include('operations.urls')),
    # 课程页面
    path('courses/', include('courses.urls')),
    # 机构页面
    path('organizations/', include('organizations.urls')),

    # 配置验证码
    path('captcha/', include('captcha.urls')),
    # 配置图片请求
    path('media/<path:path>/', serve, {'document_root': settings.MEDIA_ROOT}),

    # xadmin 第三方的富文本插件
    path('ueditor/',include('DUEditor.urls' )),

    # 配置未上线时的错误页面调试的静态文件路径
    # path('static/<path:path>/', serve, {'document_root': settings.STATIC_ROOT}),
]


# 404 错误页面 （一般是错误的 url 导致的)
handler404 = 'users.views.handler_404_error'
handler500 = 'users.views.handler_500_error'
handler403 = 'users.views.handler_403_error'

extra_apps/DUEditor/urls.py
#coding:utf-8
'''
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import url
else:
    from django.conf.urls.defaults import patterns, url


'''
from django.urls import path
from django.conf.urls import url
from .views import get_ueditor_controller


urlpatterns = [
    path('controller/', get_ueditor_controller),
]

apps/courses/models.py
# _*_ coding: utf-8 _*_

import os

from django.db import models
from django.utils import timezone
from DUEditor.models import UEditorField

from organizations.models import CourseOrganization, Teacher



# 定义动态文件的上传路径-章节
def get_upload_section_path(instance, filename):
    return os.path.join(
        'course',
        instance.chapter.course.course_name + str(instance.chapter.course_id),
        'section_content',
        instance.chapter.chapter_name,
        filename
    )


# 定义动态文件的上传路径-课程资源
def get_upload_course_resource_path(instance, filename):
    return os.path.join(
        'course',
        instance.course.course_name + str(instance.course_id),
        'course_resource',
        filename
    )


# 定义动态文件的上传路径-课程图片
def get_upload_course_image_path(instance, filename):
    return os.path.join(
        'course',
        instance.course_name + str(instance.id),
        'course_image',
        filename
    )

# 定义富文本的图片和文件上传路径-课程
def get_upload_course_ueditor_path(instance, filename):
    return os.path.join(
        'course',
        instance.course_name + str(instance.id),
        'course_description',
        filename
    )



# 定义函数，获取机构的当前的所有教师
def get_org_teachers(instance):
    teachers = CourseOrganization.objects.get(id=instance.organization_id).teacher_set.all()
    teacher_tuple = tuple([(teacher.id, teacher.teacher_name) for teacher in teachers])
    return teacher_tuple



# 课程大类模型
class CourseCategory(models.Model):
    course_category = models.CharField(max_length=20, verbose_name=u'课程大类')
    add_time = models.DateTimeField(default=timezone.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程大类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.course_category


# 课程小类模型
class CourseType(models.Model):
    course_type = models.CharField(max_length=20, verbose_name=u'课程小类')
    course_category = models.ForeignKey(
        CourseCategory,
        on_delete=models.CASCADE,
        verbose_name=u'课程小类所属的大类'
    )
    add_time = models.DateTimeField(default=timezone.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程小类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.course_type


# 课程标签
class Tags(models.Model):
    tag = models.CharField(max_length=10, verbose_name=u'标签')
    add_time = models.DateTimeField(default=timezone.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag


# 课程模型
class Course(models.Model):
    course_teacher = models.ForeignKey(
        Teacher,
        on_delete=models.CASCADE,
        verbose_name=u'课程教师',
        related_name='course_teacher'
    )
    course_type = models.ForeignKey(
        CourseType,
        on_delete=models.CASCADE,
        verbose_name=u'课程小类'
    )
    course_name = models.CharField(max_length=30, verbose_name=u'课程名称')
    description = models.TextField(max_length=50, verbose_name=u'课程描述')
    detail = UEditorField(
        verbose_name=u'课程详情',
        height=400,
        width=800,
        imagePath=get_upload_course_ueditor_path,
        filePath=get_upload_course_ueditor_path,
        default='',
        blank=True
    )
    degree = models.CharField(max_length=10, verbose_name=u'课程难度',
                              choices=(('easy', u'初级'), ('normal', u'中级'), ('hard', u'高级')))
    is_banner = models.CharField(
        choices=(('False', u'否'), ('True', u'是')),
        default='False',
        verbose_name=u'是否处于轮播位',
        max_length=10
    )
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长')
    student_number = models.IntegerField(default=0, verbose_name=u'学习人数')
    collect_number = models.IntegerField(default=0, verbose_name=u'收藏人数')
    course_mark = models.FloatField(default=10.0, verbose_name=u'课程评分')
    course_image = models.ImageField(
        upload_to=get_upload_course_image_path,
        default='course/default_image/course_default.jpg',
        max_length=500,
        verbose_name=u'课程图片',
        blank=True
    )
    open_type = models.CharField(max_length=20, verbose_name=u'课程类型', default='open',
                                   choices=(('open', u'公开课'), ('specialized', u'专业课')))
    # 点击量不同于学习人数，用于统计点击/学习转化比，每次点开一次课程，点击量加 1
    click_number = models.IntegerField(default=0, verbose_name=u'点击量')
    # 课程标签与课程的关系式 多对多
    course_tag = models.ManyToManyField(Tags, blank=True, verbose_name=u'标签')
    add_time = models.DateTimeField(default=timezone.now, verbose_name=u'课程添加时间')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.course_name


# 定义轮播课程，继承自课程
class BannerCourse(Course):

    class Meta:
        verbose_name = '轮播课程'
        verbose_name_plural = verbose_name
        proxy = True


# 章节模型
class Chapter(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程名称', on_delete=models.CASCADE)
    chapter_name = models.CharField(max_length=100, verbose_name=u'章节名称')
    add_time = models.DateTimeField(default=timezone.now, verbose_name=u'章节添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0} > {1}'.format(self.course, self.chapter_name)


# 小结模型
class Section(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, verbose_name=u'章节名')
    section_name = models.CharField(max_length=100, verbose_name=u'小节名称')
    section_content = models.FileField(
        upload_to=get_upload_section_path,
        verbose_name=u'课程小结内容文件',
        default=u''
    )
    add_time = models.DateTimeField(default=timezone.now, verbose_name=u'小节添加时间')

    class Meta:
        verbose_name = u'小节'
        verbose_name_plural = verbose_name


# 课程资源模型
class CourseResource(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u'课程相关资源')
    resource_name = models.CharField(max_length=50, verbose_name=u'资源名称')
    download = models.FileField(upload_to=get_upload_course_resource_path,
                                max_length=200, verbose_name=u'资源文件')
    add_time = models.DateTimeField(default=timezone.now, verbose_name=u'资源添加时间')

    class Meta:
        verbose_name = u'课程相关资源'
        verbose_name_plural = verbose_name


# 课程公告
class CourseAnnouncement(models.Model):
    course = models.OneToOneField(Course, on_delete=models.CASCADE, verbose_name=u'关联课程')
    course_announcement = models.CharField(max_length=200, verbose_name=u'课程公告', default=u'')
    add_time = models.DateTimeField(default=timezone.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程公告'
        verbose_name_plural = verbose_name


# 课程提示
class CourseNotice(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u'关联课程')
    course_notice = models.CharField(max_length=200, verbose_name=u'课程基础', default=u'')
    course_goal = models.CharField(max_length=200, verbose_name=u'课程目标', default=u'')
    add_time = models.DateTimeField(default=timezone.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程须知'
        verbose_name_plural = verbose_name

apps/courses/templates/courses/course-detail.html
<!DOCTYPE html>
<html>

{% extends 'base.html' %}
{% load static %}

<head>

    {% block custom_head_js %}
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
    {% endblock %}

    {% block html_title %}
        <title>课程详情 - 点点在线网</title>
    {% endblock %}

    {% block html_owner_js %}
        <script type="text/javascript">
            //收藏分享
            function add_fav(current_elem, fav_id, fav_type) {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'organizations:add_collection' %}",
                    data: {'fav_id': fav_id, 'fav_type': fav_type},
                    async: true,
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                        if (data.status === 'fail') {
                            if (data.msg === '用户未登录') {
                                window.location.href = "{% url 'users:login' %}";
                            } else {
                                alert(data.msg)
                            }

                        } else if (data.status === 'success') {
                            current_elem.text(data.msg)
                        }
                    },
                });
            }

            $(document).ready(function () {
                $('#jsLeftBtn').on('click', function () {
                    add_fav($(this), {{ course.id }}, 1);
                });
            });

            $(document).ready(function () {
                $('#jsRightBtn').on('click', function () {
                    add_fav($(this), {{ org.id }}, 2);
                });
            });

        </script>
        <script type="text/javascript">
            //开始学习
            function add_study(current_elem, course_id) {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'courses:add_course_study' %}",
                    data: {'course_id': course_id},
                    async: true,
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                        if (data.status === 'fail') {
                            if (data.msg === '用户未登录') {
                                window.location.href = "{% url 'users:login' %}";
                            } else {
                                alert(data.msg)
                            }

                        } else if (data.status === 'success') {

                        }
                    },
                });
            }
            $(document).ready(function () {
                $('#jsStudyBtn').on('click', function () {
                    add_study($(this), {{ course.id }});
                });
            });
        </script>
    {% endblock %}

</head>
<body>


<!-- 每个网页的面包屑导航，需自定义（按需体现） -->
{% block custom_breadcrumbs %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                {% if course.open_type == 'open' %}
                    <li><a href="{% url 'courses:open_courses_list' %}">公开课</a>></li>
                {% elif course.open_type == 'specialized' %}
                    <li><a href="{% url 'courses:specialized_courses_list' %}">专业课</a>></li>
                {% endif %}
                <li>课程详情</li>
            </ul>
        </div>
    </section>
{% endblock %}

<!-- 自定义页面主体 -->
{% block custom_body %}
    <section>
        <div class="wp">
            <div class="groupPurchase_detail detail">
                <div class="toppro">
                    <div class="left">
                        <div class="picbox">
                            <div class="tb-booth tb-pic">
                                <img width="440" height="250" src="
                                        {{ MEDIA_URL }}{{ course.course_image }}" class="jqzoom"/>
                            </div>
                        </div>
                        <div class="des">
                            <h1>{{ course.course_name }}</h1>
                            <span class="key">{{ course.description }}</span>
                            <div class="prize">
                                <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                <span class="fr">学习人数：{{ course.student_number }}</span>
                            </div>
                            <ul class="parameter">
                                <li>
                                    <span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{ course.learn_times }}</span>
                                </li>
                                <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span>{{ course.chapter_set.count }}</span></li>
                                <li><span class="pram word3">课程类别：</span><span>{{ course.course_type.course_category }} >>> {{ course.course_type }}</span>
                                </li>

                                <!-- 学习用户 -->
                                {% if user_studys %}
                                    <li class="piclist"><span class="pram word4">学习用户：</span>
                                        {% for user_study in user_studys %}
                                            <span class="pic">
                                                <img width="40" height="40"
                                                     src="{{ MEDIA_URL }}{{ user_study.user.head_portrait }}"/>
                                            </span>
                                        {% endfor %}
                                    </li>
                                {% endif %}

                            </ul>
                            <div class="btns">
                                <div class="btn colectgroupbtn" id="jsLeftBtn">
                                    {% if is_course_collected == '收藏' %}
                                        收藏
                                    {% else %}
                                        已收藏
                                    {% endif %}
                                </div>
                                <div class="buy btn" id="jsStudyBtn">
                                    <a style="color: white" href="{% url 'courses:course_study' course.id %}">
                                        开始学习
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="group-share-box">
                            <div class="bdsharebuttonbox"
                                 data-text="django开始了"
                                 data-desc="我在#慕课网#发现了"
                                 data-comment=""
                                 data-url="/group/groupdetail/15/">
                                <span class="fl">分享到：</span>
                                <a href="#" class="bds_more" data-cmd="more"></a>
                                <a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a>
                                <a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a>
                                <a title="分享到腾讯微博" href="#" class="bds_tqq" data-cmd="tqq"></a>
                                <a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren"></a>
                                <a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a>
                            </div>
                        </div>
                    </div>
                    <div class="right">
                        <div class="head">
                            <h1>授课机构</h1>
                            <p>世界名校，课程权威</p>
                        </div>
                        <div class="pic">
                            <a href="{% url 'organizations:organization_detail_homepage' org.id %}">
                                <img width="150" height="150" src="{{ MEDIA_URL }}{{ org.organization_image }}"/>
                            </a>
                        </div>
                        <a href="{% url 'organizations:organization_detail_homepage' org.id %}">
                            <h2 class="center">{{ org.organization_name }}</h2>
                        </a>
                        <div class="btn  notlogin" data-favid="14" id="jsRightBtn">
                            {% if is_organization_collected == '收藏' %}
                                收藏
                            {% else %}
                                已收藏
                            {% endif %}
                        </div>
                        <div class="clear">
                            <ul>
                                <li>
                                    <span>课&nbsp;程&nbsp;数：{{ org.get_course_number_org }}</span>
                                </li>
                                <li>
                                    <span>教&nbsp;师&nbsp;数：{{ org.teacher_set.count }}</span>
                                </li>
                                <li>所在地区：{{ org.city }}</li>
                                <li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证:
                                    <img title="金牌机构" src="{% static 'images/gold.png' %}"/>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="wp">
            <div class="list groupPurchase_detail_pro">
                <div class="left layout">
                    <div class="head">
                        <ul class="tab_header">
                            <li class="active">课程详情</li>
                        </ul>
                    </div>
                    <div class="tab_cont tab_cont1">

                        {% autoescape off %}
                            {{ course.detail }}
                        {% endautoescape %}

                    </div>
                    <div class="tab_cont tab_cont2">
                        <div class="comment">
                            <div class="comenlist">

                            </div>
                        </div>
                    </div>
                </div>
                <div class="right layout">
                    <div class="head">相关课程推荐</div>
                    <div class="group_recommend">

                        {% for same_course in same_courses %}
                            <dl>
                                <dt>
                                    <a target="_blank" href="{% url 'courses:course_detail' same_course.id %}">
                                        <img width="240" height="120" class="scrollLoading" src="{{ MEDIA_URL }}{{ same_course.course_image }}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <a target="_blank" href=""><h2>{{ same_course.course_ame }}</h2></a>
                                    <span class="fl">收藏人数：<i class="key">{{ same_course.collect_number }}</i></span>
                                </dd>
                            </dl>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}


</body>
</html>