apps/courses/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/25 21:47'

from django.urls import path


from . import views

app_name = 'courses'

urlpatterns = [
    path('specialized_courses_list/', views.SpecializedCoursesList.as_view(), name='specialized_courses_list'),
    path('open_courses_list/', views.OpenCoursesList.as_view(), name='open_courses_list'),
    path('course_detail/<int:course_id>/', views.CourseDetail.as_view(), name='course_detail'),

    # 课程学习
    path('course_study/<int:course_id>/', views.CourseStudy.as_view(), name='course_study'),
    # 课程评论
    path('course_comment/<int:course_id>/', views.CourseCommentView.as_view(), name='course_comment'),
    # 添加课程评论
    path('add_course_comment/', views.AddCourseCommentView.as_view(), name='add_course_comment'),
    # 添加课程到用户的学习表
    path('add_course_study',views.AddCourseStudy.as_view(), name='add_course_study'),
    # 课程的章节学习页面
    path('course_study_detail/<int:course_id>/<int:section_id>/', views.CourseStudyDetail.as_view(), name='course_study_detail'),
]

apps/operations/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/25 18:14'

from django.urls import path
from . import views

app_name = 'operations'

urlpatterns = [
    # 用户个人中心
    path('user_center_information/', views.UserCenterInformation.as_view(), name='user_center_information'),

    # 用户学习的课程
    path('user_center_my_courses/', views.UserStudyCourse.as_view(), name='user_center_my_courses'),

    # 用户消息
    path('user_center_messages/', views.UserMessageView.as_view(), name='user_center_messages'),

    # 用户收藏的教师
    path('user_center_fav_teachers/', views.UserCollectedTeacher.as_view(), name='user_center_fav_teachers'),
    # 用户收藏的教师
    path('user_center_fav_courses/', views.UserCollectedCourse.as_view(), name='user_center_fav_courses'),
    # 用户收藏的教师
    path('user_center_fav_organizations/', views.UserCollectedOrganization.as_view(), name='user_center_fav_organizations'),

    # 修改用户头像
    path('reset_head_portrait/', views.ResetUserHeaderPortraitView.as_view(), name='reset_head_portrait'),
    # 修改用户密码
    path('reset_user_password/', views.ResetUserPasswordView.as_view(), name='reset_user_password'),
    # 修改用户信息
    path('reset_user_information/', views.ResetUserInformationView.as_view(), name='reset_user_information'),
    # 修改邮箱是发送的验证码
    path('send_email_verify_record/', views.SendEmailView.as_view(), name='send_email_verify_record'),
    # 修改邮箱
    path('reset_user_email/', views.ResetUserEmailView.as_view(), name='reset_user_email'),

    # 读取用户消息
    path('read_message/', views.ReadMessageView.as_view(), name='read_message'),


]

apps/organizations/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/25 21:47'

from django.urls import path

from . import views

app_name = 'organizations'

urlpatterns = [
    # 课程机构列表
    path('organizations_list/', views.OrganizationsList.as_view(), name='organizations_list'),
    # 课程咨询
    path('add_ask/', views.AddUserAsk.as_view(), name='add_ask'),
    # 机构详情
    path('organization_detail_homepage/<int:org_id>/', views.OrganizationHomePage.as_view(), name='organization_detail_homepage'),
    path('organization_detail_courses/<int:org_id>/', views.OrganizationCoursePage.as_view(), name='organization_detail_courses'),
    path('organization_detail_teachers/<int:org_id>/', views.OrganizationTeacherPage.as_view(), name='organization_detail_teachers'),
    path('organization_detail_description/<int:org_id>/', views.OrganizationDescripthionPage.as_view(), name='organization_detail_description'),
    # 收藏功能
    path('add_collection', views.AddCollection.as_view(), name='add_collection'),


    path('teacher_detail/<int:teacher_id>', views.TeacherInformation.as_view(), name='teacher_detail'),
    path('teachers_list/', views.TeacherList.as_view(), name='teachers_list'),
]

apps/users/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/20 19:52'

from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    # path('', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('active/<slug:active_code>/', views.ActiveCode.as_view(), name='user_active'),
    path('forget_password/', views.ForgetPassword.as_view(), name='forget_password'),
    path('forget/<slug:user_name>/<slug:forget_password_code>/', views.ForgetPassWordCode.as_view(), name='reset_password_verify'),
    path('reset_password/', views.ResetPassword.as_view(), name='reset_password'),

]

diandian_online/urls.py
# _*_ coding: utf-8 _*_

"""diandian_online URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import xadmin
from django.views.generic import TemplateView

# 静态文件请求的处理
from django.views.static import serve
from diandian_online import settings
from apps.users import views


urlpatterns = [

    # 首页
    path('', views.Index.as_view(), name='index'),
    # xadmin 的后台
    path('xadmin/', xadmin.site.urls),

    # 用户相关的页面
    path('users/', include('users.urls')),
    # 用户操作相关的页面
    path('operations/', include('operations.urls')),
    # 课程页面
    path('courses/', include('courses.urls')),
    # 机构页面
    path('organizations/', include('organizations.urls')),

    # 配置验证码
    path('captcha/', include('captcha.urls')),
    # 配置图片请求
    path('media/<path:path>/', serve, {'document_root': settings.MEDIA_ROOT}),

    # xadmin 第三方的富文本插件
    path('ueditor/',include('DUEditor.urls' )),

    # 配置未上线时的错误页面调试的静态文件路径
    # path('static/<path:path>/', serve, {'document_root': settings.STATIC_ROOT}),
]


# 404 错误页面 （一般是错误的 url 导致的)
handler404 = 'users.views.handler_404_error'
handler500 = 'users.views.handler_500_error'
handler403 = 'users.views.handler_403_error'

extra_apps/DUEditor/urls.py
#coding:utf-8
'''
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import url
else:
    from django.conf.urls.defaults import patterns, url


'''
from django.urls import path
from django.conf.urls import url
from .views import get_ueditor_controller


urlpatterns = [
    path('controller/', get_ueditor_controller),
]

templates/base.html
<!DOCTYPE html>
<html>

{% load static %}

<head>

    <!-- 页头公共部分 -->
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!-- 网页的 favicon.ico 文件,若不申明，浏览器中 F12 会发现 favicon.ico 加载错误-->
    <!-- 错误详情 "GET /favicon.ico HTTP/1.1" 404 Not Found: /favicon.ico -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <!-- 自定义「js」文件引用声明,jQuery 需要在最前面进行申明 -->
    {% block custom_head_js %}
    {% endblock %}

    <!-- 页面专属「js」文件 需自定义(代码直接写在「html文件」中)-->
    {% block html_owner_js %}
    {% endblock %}


    <script type='text/javascript' src="{% static 'js/selectUi.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/deco-common.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/layer/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/queryCity/js/public.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/unslider.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/jquery.scrollLoading.js' %}"></script>


    {% comment %}
    「html」页面使用了「ajax」进行异步数据的请求与响应时，会产生「403」错误。经查询，「django」的官方提供以解决方案
    将官方给出的代码保存到一个「js文件」中，并在「html」页面中导入
    记得一定要在加载完「jQuery」之后加载
    {% endcomment %}
    <script type="text/javascript" src="{% static 'js/crsf_ajax.js' %}"></script>


    <!-- 页面标题每个页面需自定义 -->
	{% block html_title %}<title>点点在线网 - 首页</title>{% endblock %}

    <!-- 自定义「css」文件引用声明 -->
    {% block custom_head_css %}
    {% endblock %}


</head>

<body>
    <!-- 页眉数据，部分公用, 内部包含页眉定制数据 -->
    <section class="headerwrap">
        <header>
            <div  class="header">
                <!-- 顶部页眉，公用 -->
                {% if not request.user.is_authenticated %}
                    <div class="top">
                        <div class="wp">
                            <div class="fl">
                                <p>服务电话：<b>4008888888</b></p>
                            </div>
                            <a style="color:white" class="fr registerbtn" href="{% url 'users:register' %}">注册</a>
                            <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
                        </div>
                    </div>
                {% else %}
                    <div class="top">
                        <div class="wp">
                            <div class="fl"><p>服务电话：<b>4008888888</b></p></div>
                            <!--登录后跳转-->
                            <div class="personal">
                                <dl class="user fr">
                                    <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                    <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.head_portrait }}"/></dt>
                                </dl>
                                <div class="userdetail">
                                    <dl>
                                        <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.head_portrait }}"/></dt>
                                        <dd>
                                            <h2>django</h2>
                                            <p>{{ request.user.username }}</p>
                                        </dd>
                                    </dl>
                                    <div class="btn">
                                        <a class="personcenter fl" href="{% url 'operations:user_center_information' %}">进入个人中心</a>
                                        <a class="fr" href="{% url 'users:logout' %}">退出</a>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'operations:user_center_messages' %}">
                                <div class="msg-num"><span id="MsgNum">{{ request.user.get_user_unread_messages }}</span></div>
                            </a>
                        </div>
			        </div>
                {% endif %}
                <!-- logo 和 搜索框 -->
                <div class="middle">
                    <div class="wp">
                        <a href="{% url 'index' %}">
                            <img class="headerlogo fl" src="{% static 'images/logo.jpg' %}"/>
                        </a>
                        <div class="searchbox fr">
                            <div class="selectContainer fl">
                                <span class="selectOption" id="jsSelectOption" data-value="open_course">
                                    公开课
                                </span>
                                <ul class="selectMenu" id="jsSelectMenu">
                                    <li data-value="open_course">公开课</li>
                                    <li data-value="specialized_course">专业课</li>
                                    <li data-value="org">课程机构</li>
                                    <li data-value="teacher">授课老师</li>
                                </ul>
                            </div>
                            <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                            <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                        </div>
                    </div>
                </div>
                <!-- 自定义导航栏 -->
                <nav>
                    <div class="nav">
                        <div class="wp">
                            <ul>
                                <li class="{% if focus == 'index' %}active{% endif %}">
                                    <a href="{% url 'index' %}">
                                        首页
                                    </a>
                                </li>
                                <li class={% if focus == 'open' %}"active"{% endif %}>
                                    <a href="{% url 'courses:open_courses_list' %}">
                                        公开课
                                        <img class="hot" src="{% static 'images/nav_hot.png' %}">
                                    </a>
                                </li>
                                <li class={% if focus == 'specialized' %}"active"{% endif %}>
                                    <a href="{% url 'courses:specialized_courses_list' %}">
                                        专业课
                                    </a>
                                </li>
                                <li class={% if focus == 'teacher' %}"active"{% endif %}>
                                    <a href="{% url 'organizations:teachers_list' %}">
                                        授课教师
                                    </a>
                                </li>
                                <li class={% if focus == 'organization' %}"active"{% endif %}>
                                    <a href="{% url 'organizations:organizations_list' %}">
                                        授课机构
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </header>
    </section>

    <!-- 每个网页的面包屑导航，需自定义（按需体现） -->
    {% block custom_breadcrumbs %}
    {% endblock %}


    <!-- 每个网页的页面主体，需自定义 -->
    {% block custom_body %}
    {% endblock %}


    <!-- 回到顶部（按需体现） -->
    {% block back_to_top %}
        <section>
            <ul class="sidebar">
                <li class="qq">
                    <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
                </li>
                <li class="totop"></li>
            </ul>
        </section>
    {% endblock %}


    <!-- 页脚，公用 -->
    <footer>
        <div class="footer">
            <div class="wp">
                <ul class="cont">
                    <li class="logo">
                        <a href="{% url 'index' %}">
                            <img class="footlogo" src="{% static 'images/footlogo.png' %}"/>
                        </a>
                    </li>
                    <li class="code">
                        <img src="{% static 'images/code.jpg' %}"/>
                        <p class="center">扫描关注微信</p>
                    </li>
                    <li class="third">
                        <img class="fl" src="{% static 'images/tell.png' %}"/>
                        <p class="tell">4008888888</p>
                        <p class="time">周一至周日 9:00-18:00</p>
                    </li>
                </ul>
            </div>
            <p class="line"></p>
            <div class="wp clear">
                <span class="fl">2019 www.ddianonline.com 点点在线-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright 2019 ICP备案证书号：浙ICP备888888号-1</span>
            </div>
        </div>
    </footer>

</body>
</html>

templates/base_http_fail.html
<!DOCTYPE html>
<html>

{% load static %}

<head>
	<meta charset="UTF-8">
	<title>404</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
</head>

{% block custom_body %}
{% endblock %}

</html>

templates/base_org_home_page.html
<!DOCTYPE html>
<html>

{% load static %}

<head>

    <!-- 页头公共部分 -->
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">


    <!-- 网页的 favicon.ico 文件,若果不申明，浏览器中 F12 会发现 favicon.ico 加载错误-->
    <!-- 错误详情 "GET /favicon.ico HTTP/1.1" 404 Not Found: /favicon.ico -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <!-- 自定义「js」文件引用声明,jQuery 需要在最前面进行申明 -->
    {% block custom_head_js %}
    {% endblock %}

    <!-- 页面专属「js」文件 需自定义(代码直接写在「html文件」中)-->
    {% block html_owner_js %}
    {% endblock %}


    <script type='text/javascript' src="{% static 'js/selectUi.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/deco-common.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/layer/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/queryCity/js/public.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/unslider.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/jquery.scrollLoading.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
    <script type="text/javascript">
        //收藏分享
        function add_fav(current_elem, fav_id, fav_type) {
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'organizations:add_collection' %}",
                data: {'fav_id': fav_id, 'fav_type': fav_type},
                async: true,
                {% comment %}
                这里是 js 的写法，由于收藏功能并没有写在「form」标签中，所以要在这里添加上「csrf_token」
                 -> {% csrf_token %} 会在「html」中生成一段「html代码」
                 -> {{ csrf_token }} 则是取出「csrf_token」的值
                {% endcomment %}
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    if (data.status === 'fail') {
                        if (data.msg === '用户未登录') {
                            window.location.href = "{% url 'users:login' %}";
                        } else {
                            alert(data.msg)
                        }
                    } else if (data.status === 'success') {
                        current_elem.text(data.msg)
                    }
                },
            });
        }

        $(document).ready(function () {
            {# 监控按钮「collection」的点击事件 #}
            $('.collectionbtn').on('click', function () {
                {#参数：第一个是机构的「id」，第二个是收藏的类型「2代表收藏的类型是 课程机构」#}
                add_fav($(this), {{ org_id }}, 2);
            });
        });
        $(function () {
            var $precision = $('.precision'),
                score = $precision.attr('data-star-scope'),
                option = {
                    half: true,
                    path: '{% static 'images' %}',
                    precision: true,
                    size: 24,
                    starOff: 'g_star.png',
                    starOn: 'r_star.png',
                    starHalf: 'h_star.png',
                    hints: ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg: '暂时还未获得评价！',
                    readOnly: true,
                    score: score
                };
            $precision.raty(option);

            $(document).ready(function () {
                $('.jsFavBtn').on('click', function () {
                    var type = $(this).attr('data-fav-type');
                    if (type === '1') {
                        favPraise($(this), 'fav', 1, '收藏');

                    } else if (type === '3') {
                        favPraise($(this), 'fav', 3);

                    } else if (type === '11') {
                        favPraise($(this), 'pra', 1);

                    } else if (type === '4') {
                        favPraise($(this), 'fav', 4);

                    }
                });
            });
        })
    </script>
    <script type="text/javascript">
        $(function () {
            $('.recordbtn1').click(function () {
                $('.recordbox1').show();
            });
            $('.recordbtn2').click(function () {
                $('.recordbox2').show();
            });

            $('.imgslide').unslider({
                speed: 500,               //  The speed to animate each slide (in milliseconds)
                delay: 3000,              //  The delay between slide animations (in milliseconds)
                complete: function () {
                },  //  A function that gets called after every slide animation
                keys: true,               //  Enable keyboard (left, right) arrow shortcuts
                dots: true,               //  Display dot navigation
                fluid: false              //  Support responsive design. May break non-responsive designs
            });
            var unslider = $('.imgslide').unslider();
            $('.unslider-arrow').click(function () {
                var fn = this.className.split(' ')[1];
                unslider.data('unslider')[fn]();
            });
        });
    </script>


    {% comment %}
    「html」页面使用了「ajax」进行异步数据的请求与响应时，会产生「403」错误。经查询，「django」的官方提供以解决方案
    将官方给出的代码保存到一个「js文件」中，并在「html」页面中导入
    记得一定要在加载完「jQuery」之后加载
    {% endcomment %}
    <script type="text/javascript" src="{% static 'js/crsf_ajax.js' %}"></script>


    <!-- 页面标题每个页面需自定义 -->
    {% block html_title %}<title>点点在线网 - 首页</title>{% endblock %}

    <!-- 自定义「css」文件引用声明 -->
    {% block custom_head_css %}
    {% endblock %}


</head>

<body>
<!-- 页眉数据，部分公用, 内部包含页眉定制数据 -->
<section class="headerwrap headerwrap2">
    <header>
        <div class="header2 header">

            <!-- 顶部页眉，公用 -->
            {% if not request.user.is_authenticated %}
                <div class="top">
                    <div class="wp">
                        <div class="fl">
                            <p>服务电话：<b>4008888888</b></p>
                        </div>
                        <a style="color:white" class="fr registerbtn" href="{% url 'users:register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
                    </div>
                </div>
            {% else %}
                <div class="top">
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>4008888888</b></p></div>
                        <!--登录后跳转-->
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/>
                                </dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.head_portrait }}"/>
                                </dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="
                                            {{ MEDIA_URL }}{{ request.user.head_portrait }}"/></dt>
                                    <dd>
                                        <h2>django</h2>
                                        <p>{{ request.user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'operations:user_center_information' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'users:logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'operations:user_center_messages' %}">
                            <div class="msg-num"><span id="MsgNum">{{ request.user.get_user_unread_messages}}</span></div>
                        </a>
                    </div>
                </div>
            {% endif %}

            <!-- 机构logo -->
            <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ org_info.organization_image }}"/>
            <div class="head fl">
                <h1>
                    {{ org_info.organization_name }}
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">机构评价： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">{{ org_info.organization_mark }}</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin" data-favid="22" data-fav-type="1">
                {{ is_collected }}
            </div>
        </div>
    </div>

        </div>
    </header>
</section>

<!-- 每个网页的面包屑导航，需自定义（按需体现） -->
{% block custom_breadcrumbs %}
{% endblock %}


<!-- 每个网页的页面主体，需自定义 -->
<section>
    <div class="wp list personal_list comp">
        <div class="left">
            <ul>
                <li class={% if left_focus == 'home' %}"active2"{% endif %}>
                    <a href="{% url 'organizations:organization_detail_homepage' org_id %}">机构首页</a>
                </li>
                <li class={% if left_focus == 'course' %}"active2"{% endif %}>
                    <a href="{% url 'organizations:organization_detail_courses' org_id %}">机构课程</a>
                </li>
                <li class={% if left_focus == 'teacher' %}"active2"{% endif %}>
                    <a href="{% url 'organizations:organization_detail_teachers' org_id %}">机构讲师</a>
                </li>
                <li class={% if left_focus == 'description' %}"active2"{% endif %}>
                    <a href="{% url 'organizations:organization_detail_description' org_id %}">机构介绍</a>
                </li>
            </ul>
        </div>
        <!-- 页面右侧主体内容 -->
        {% block custom_right_body %}
        {% endblock %}

</section>



<!-- 回到顶部（按需体现） -->
{% block back_to_top %}
    <section>
        <ul class="sidebar">
            <li class="qq">
                <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
            </li>
            <li class="totop"></li>
        </ul>
    </section>
{% endblock %}

</body>
</html>