apps/courses/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/25 21:47'

from django.urls import path


from . import views

app_name = 'courses'

urlpatterns = [
    path('specialized_courses_list/', views.SpecializedCoursesList.as_view(), name='specialized_courses_list'),
    path('open_courses_list/', views.OpenCoursesList.as_view(), name='open_courses_list'),
    path('course_detail/<int:course_id>/', views.CourseDetail.as_view(), name='course_detail'),

    # 课程学习
    path('course_study/<int:course_id>/', views.CourseStudy.as_view(), name='course_study'),
    # 课程评论
    path('course_comment/<int:course_id>/', views.CourseCommentView.as_view(), name='course_comment'),
    # 添加课程评论
    path('add_course_comment/', views.AddCourseCommentView.as_view(), name='add_course_comment'),
    # 添加课程到用户的学习表
    path('add_course_study',views.AddCourseStudy.as_view(), name='add_course_study'),
    # 课程的章节学习页面
    path('course_study_detail/<int:course_id>/<int:section_id>/', views.CourseStudyDetail.as_view(), name='course_study_detail'),
]

apps/organizations/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/25 21:47'

from django.urls import path

from . import views

app_name = 'organizations'

urlpatterns = [
    # 课程机构列表
    path('organizations_list/', views.OrganizationsList.as_view(), name='organizations_list'),
    # 课程咨询
    path('add_ask/', views.AddUserAsk.as_view(), name='add_ask'),
    # 机构详情
    path('organization_detail_homepage/<int:org_id>/', views.OrganizationHomePage.as_view(), name='organization_detail_homepage'),
    path('organization_detail_courses/<int:org_id>/', views.OrganizationCoursePage.as_view(), name='organization_detail_courses'),
    path('organization_detail_teachers/<int:org_id>/', views.OrganizationTeacherPage.as_view(), name='organization_detail_teachers'),
    path('organization_detail_description/<int:org_id>/', views.OrganizationDescripthionPage.as_view(), name='organization_detail_description'),
    # 收藏功能
    path('add_collection', views.AddCollection.as_view(), name='add_collection'),


    path('teacher_detail/<int:teacher_id>', views.TeacherInformation.as_view(), name='teacher_detail'),
    path('teachers_list/', views.TeacherList.as_view(), name='teachers_list'),
]

diandian_online/urls.py
# _*_ coding: utf-8 _*_

"""diandian_online URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import xadmin
from django.views.generic import TemplateView

# 静态文件请求的处理
from django.views.static import serve
from diandian_online import settings
from apps.users import views


urlpatterns = [

    # 首页
    path('', views.Index.as_view(), name='index'),
    # xadmin 的后台
    path('xadmin/', xadmin.site.urls),

    # 用户相关的页面
    path('users/', include('users.urls')),
    # 用户操作相关的页面
    path('operations/', include('operations.urls')),
    # 课程页面
    path('courses/', include('courses.urls')),
    # 机构页面
    path('organizations/', include('organizations.urls')),

    # 配置验证码
    path('captcha/', include('captcha.urls')),
    # 配置图片请求
    path('media/<path:path>/', serve, {'document_root': settings.MEDIA_ROOT}),

    # xadmin 第三方的富文本插件
    path('ueditor/',include('DUEditor.urls' )),

    # 配置未上线时的错误页面调试的静态文件路径
    # path('static/<path:path>/', serve, {'document_root': settings.STATIC_ROOT}),
]


# 404 错误页面 （一般是错误的 url 导致的)
handler404 = 'users.views.handler_404_error'
handler500 = 'users.views.handler_500_error'
handler403 = 'users.views.handler_403_error'

extra_apps/DUEditor/urls.py
#coding:utf-8
'''
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import url
else:
    from django.conf.urls.defaults import patterns, url


'''
from django.urls import path
from django.conf.urls import url
from .views import get_ueditor_controller


urlpatterns = [
    path('controller/', get_ueditor_controller),
]

apps/organizations/forms.py
# _*_ coding: utf-8 _*_
__author__ = 'nick'
__date__ = '2019/2/28 23:11'

import re

from django import forms

from operations.models import UserAsk


class UserAskForm(forms.ModelForm):

    class Meta:
        model = UserAsk
        fields = ['name', 'mobile', 'course_name']

    def clean_mobile(self):
        """
        验证手机号码是否合法
        """
        mobile = self.cleaned_data['mobile']
        regex = r'^1[3|4|5|7|8]\d{9}$'
        pattern = re.compile(regex)
        if pattern.match(mobile):
            return mobile
        else:
            raise forms.ValidationError(u'无效的手机号码', code='mobile_invalid')

apps/organizations/views.py
# _*_ coding: utf-8 _*_

import re

from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse, HttpResponse
from django.db.models import Q

# 分页功能组件（第三方）
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

from .models import CourseOrganization, CityDict, Teacher
from courses.models import Course
from .forms import UserAskForm
from operations.models import UserCollection, UserMessage



# 定义增加或取消收藏
def add_or_cancel_collection(type, collection_id, collection_type):
    id = {
        '1': Course,
        '2': CourseOrganization,
        '3': Teacher,
    }
    model_instance = id.get(str(collection_type))
    model_instance = model_instance.objects.get(id=collection_id)
    if type == 'add':
        model_instance.collect_number += 1
        model_instance.save()
    elif type == 'cancel':
        model_instance.collect_number -= 1
        if model_instance.collect_number < 0:
            model_instance.collect_number = 0
        model_instance.save()


# 定义用户收藏，添加收藏消息到用户消息表中
def add_collection_message_to_user_message(user_id, collection_id, collection_type):
    id = {
        '1': Course,
        '2': CourseOrganization,
        '3': Teacher,
    }
    model_instance = id.get(str(collection_type))
    model_instance = model_instance.objects.get(id=collection_id)
    user_message = UserMessage()
    user_message.user = user_id
    name = ''
    if collection_type == 1:
        name = model_instance.course_name
    elif collection_type == 2:
        name = model_instance.organization_name
    elif collection_type == 3:
        name = model_instance.teacher_name

    user_message.message = "欢迎你收藏<{}\n{}>".format(name, model_instance.description)
    user_message.save()


# 课程机构列表
class OrganizationsList(View):
    def get(self, request):
        # 获取所有的培训机构数据和城市数据
        all_orgs = CourseOrganization.objects.all().order_by('-collect_number')
        all_citys = CityDict.objects.all()
        # 获取 3 家热门机构，以收藏数为准
        hot_args = all_orgs[:3]

        # 课程搜索关键字
        # 使用 django 的 ORM 中的 __icontains，它会在数据库中生成 like 的语句进行匹配
        # i 标识不区分大小写
        search_keyword = request.GET.get('keywords', '')
        if search_keyword:
            all_orgs = all_orgs.filter(
                Q(organization_name__icontains=search_keyword) |
                Q(description__icontains=search_keyword)|
                Q(city__city_name__icontains=search_keyword)
            )

        # 页面数据筛选
        # 获取培训机构类型筛选数据
        org_type = request.GET.get('ct', '')
        if org_type:
            all_orgs = all_orgs.filter(organization_type=org_type)

        # 获取培训机构地址筛选数据
        city_id = request.GET.get('city', '')
        if city_id:
            all_orgs = all_orgs.filter(city_id=int(city_id))

        count = all_orgs.count()

        # 机构排序
        sort = request.GET.get('sort', '')
        if sort == 'students':
            all_orgs = all_orgs.order_by('-students')
        elif sort == 'courses':
            all_orgs = all_orgs.order_by('-course_number')

        # 实现分页功能
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_orgs, 6, request=request)

        org_list = p.page(page)

        return render(request, 'organizations/org-list.html', {
            'all_orgs': org_list,
            'all_citys': all_citys,
            'city_id': city_id,
            'org_type': org_type,
            'count': count,
            'sort': sort,
            'hot_orgs': hot_args,
            'focus': 'organization'
        })


# 用户添加问询
class AddUserAsk(View):
    # 异步操作，不刷新页面，返回的是 JsonResponse
    # 使用「form」表单搭配「js」中的「ajax」来实现
    # 「ajax」使用时会出现「403」错误，通过官方提供的方法已解决，可查看「base.html」中的说明
    def post(self, request):
        user_ask_form = UserAskForm(request.POST)
        if user_ask_form.is_valid():
            user_ask_form.save(commit=True)
            return JsonResponse({'status': 'success'})
        else:
            response = {'status': 'fail', 'msg': '信息填写有误，请重新填写'}
            # response = {'status': 'fail', 'msg': '{0}'.format(user_ask_form.errors)}
            return JsonResponse(response)


class OrganizationHomePage(View):
    """
    机构首页
    """
    def get(self, request, org_id):

        # 通过机构的 主键id 从机构数据表中获取机构的相关数据
        org_info = CourseOrganization.objects.get(id=org_id)

        # 进入机构，机构的点击数加 1
        org_info.click_number += 1
        org_info.save()

        # 通过机构的数据，在课程数据表中获取该机构的所有课程
        # 使用 __in 方式查询存在于一个list范围内的所有值
        courses = Course.objects.filter(
            course_teacher__in=[teacher.id for teacher in org_info.teacher_set.all()]
        ).order_by('-collect_number')[:3]
        # 机构的id 在教师数据表中获取教师的信息
        teachers = Teacher.objects.filter(organization_id=org_id).order_by('-collect_number')[:3]
        # 简版的机构简介
        description = org_info.description[:200]

        if request.user.is_authenticated:
            # 增加用户收藏状态的判断
            collection = UserCollection.objects.filter(user = request.user, collection_id=org_id, collection_type=2)
            if collection:
                is_collected = u'已收藏'
            else:
                is_collected = u'收藏'
        else:
            is_collected = u'收藏'

        return render(request, 'organizations/org-detail-homepage.html', {
            'org_info': org_info,
            'courses': courses,
            'teachers': teachers,
            'org_id': org_id,
            'description': description,
            'is_collected': is_collected,
            # 选中项变色
            'left_focus': 'home',
            'focus': 'organization',
        })


class OrganizationCoursePage(View):
    """
    机构课程
    """
    def get(self, request, org_id):
        # 通过机构的 主键 id 从机构数据表中获取机构的相关数据
        org_info = CourseOrganization.objects.get(id=org_id)
        # 通过机构的数据，在课程数据表中获取该机构的所有课程
        courses = Course.objects.filter(
            course_teacher__in=[teacher.id for teacher in org_info.teacher_set.all()]
        ).order_by('-collect_number')

        if request.user.is_authenticated:
            # 增加用户收藏状态的判断
            collection = UserCollection.objects.filter(user=request.user, collection_id=org_id, collection_type=2)
            if collection:
                is_collected = u'已收藏'
            else:
                is_collected = u'收藏'
        else:
            is_collected = u'收藏'

        # 实现分页功能
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(courses, 6, request=request)

        courses_list = p.page(page)

        return render(request, 'organizations/org-detail-courses.html', {
            'org_info': org_info,
            'courses': courses_list,
            'org_id': org_id,
            'is_collected': is_collected,
            # 选中项变色
            'left_focus': 'course',
            'focus': 'organization',
        })


class OrganizationTeacherPage(View):
    """
    机构教师
    """
    def get(self, request, org_id):
        # 通过机构的 主键id 从机构数据表中获取机构的相关数据
        org_info = CourseOrganization.objects.filter(id=org_id)[0]
        # 机构的id 在教师数据表中获取教师的信息
        teachers = Teacher.objects.filter(organization_id=org_id).order_by('-collect_number')

        if request.user.is_authenticated:
            # 增加用户收藏状态的判断
            collection = UserCollection.objects.filter(user=request.user, collection_id=org_id, collection_type=2)
            if collection:
                is_collected = u'已收藏'
            else:
                is_collected = u'收藏'
        else:
            is_collected = u'收藏'

        # 实现分页功能
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(teachers, 6, request=request)

        teachers_list = p.page(page)

        return render(request, 'organizations/org-detail-teachers.html', {
            'org_info': org_info,
            'teachers': teachers_list,
            'org_id': org_id,
            'is_collected': is_collected,
            # 选中项变色
            'left_focus': 'teacher',
            'focus': 'organization',
        })

class OrganizationDescripthionPage(View):
    """
    机构描述
    """
    def get(self, request, org_id):
        # 通过机构的 主键id 从机构数据表中获取机构的相关数据
        org_info = CourseOrganization.objects.filter(id=org_id)[0]

        if request.user.is_authenticated:
            # 增加用户收藏状态的判断
            collection = UserCollection.objects.filter(user=request.user, collection_id=org_id, collection_type=2)
            if collection:
                is_collected = u'已收藏'
            else:
                is_collected = u'收藏'
        else:
            is_collected = u'收藏'

        return render(request, 'organizations/org-detail-desc.html', {
            'org_info': org_info,
            'org_id': org_id,
            'is_collected': is_collected,
            # 选中项变色
            'left_focus': 'description',
            'focus': 'organization',
        })


class AddCollection(View):
    """
    用户收藏或取消收藏
    """
    def post(self, request):
        # 获取收藏类型和所要添加到数据表的id
        collection_id = int(request.POST.get('fav_id', 0))
        collection_type = int(request.POST.get('fav_type', 0))

        # 判断用户的登录状态
        # request 对象中有一个 user 中有一个属性 is_authenticated，如果是处于未登录状态，值是 False
        if not request.user.is_authenticated:
            return JsonResponse({'status': 'fail', 'msg': u'用户未登录'})

        # 进入数据库查找用户的收藏记录
        exist_records = UserCollection.objects.filter(
            user=request.user,
            collection_id=collection_id,
            collection_type=collection_type
        )
        if exist_records:
            # 如果为True，记录已存在，则是用户取消收藏，执行删除操作，
            # 相应的课程或机构或教师的收藏数减 1
            add_or_cancel_collection('cancel', collection_id, collection_type)
            exist_records.delete()
            return JsonResponse({'status': 'success', 'msg': u'收藏'})
        else:

apps/organizations/templates/organizations/org-detail-homepage.html
<!DOCTYPE html>
<html>

{% extends 'base_org_home_page.html' %}
{% load static %}

<head>

    <!-- 页面标题每个页面需自定义 -->
    {% block html_title %}<title>授课机构主页 - 点点在线网</title>{% endblock %}

    <!--网页自定义的外联js-->
    {% block custom_head_js %}
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
    {% endblock %}

</head>
<body>


<!-- 每个网页的面包屑导航，需自定义（按需体现） -->
{% block custom_breadcrumbs %}

    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'organizations:organizations_list' %}">课程机构</a>></li>
                <li>机构首页</li>
            </ul>
        </div>
    </section>

{% endblock %}

<!-- 页面右侧主体内容 -->
{% block custom_right_body %}

    <div class="right companycenter layout grouping">
        <div class="head">
            <h1>机构课程</h1>
            <a class="green fr more" href="{% url 'organizations:organization_detail_courses' org_id %}">查看更多 > </a>
        </div>
        <div class="brief group_list">

            {% for course in courses %}
                <div class="module1_5 box">
                    <a href="{% url 'courses:course_detail' course.id %}">
                        <img width="214" src="{{ MEDIA_URL }}{{ course.course_image }}"/>
                    </a>
                    <div class="des">
                        <a href="{% url 'courses:course_detail' course.id %}">
                            <h2>{{ course.course_name }}</h2>
                        </a>
                        <span class="fl">课时：<i class="key">{{ course.learn_times }}</i></span>
                        <span class="fr">参加人数：{{ course.student_number }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ course.course_teacher.organization }}</span>
                        <span class="star fr  notlogin
                                    " data-favid="13" data-fav-type="4">
                                    {{ course.collect_number }}
                                </span>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构教师</h1>
            <a class="green fr more" href="{% url 'organizations:organization_detail_teachers' org_id %}">查看更多 > </a>
        </div>

        <div class="diarys">

            {% for teacher in teachers %}
                <div class="module5 share company-diary-box" style="padding:10px 0;">

                    <div class="left">
                        <a href="{% url 'organizations:teacher_detail' teacher.id %}">
                            <img class="pic" src="{{ MEDIA_URL }}{{ teacher.teacher_image }}"/>
                            <p>姓名：{{ teacher.teacher_name }}</p>
                        </a>
                    </div>
                    <div class="right">
                        <div class="top">
                            <div class="fl">
                                <a href="{% url 'courses:course_detail' teacher.get_valuable_course.id %}">
                                    <h1>{{ teacher.get_valuable_course.course_name }}</h1>
                                </a>
                                <span>发表于：{{ teacher.get_valuable_course.add_time|date:"SHORT_DATE_FORMAT" }}</span>
                            </div>
                        </div>
                        <div class="middle" style="border-bottom:0;">
                            课程介绍: {{ teacher.get_valuable_course.description }}
                        </div>
                    </div>

                </div>
            {% endfor %}

        </div>

    </div>

    <div class="right companycenter layout">
        <div class="head">
            <h1>机构介绍</h1>
            <a class="green fr more" href="{% url 'organizations:organization_detail_description' org_id %}">查看更多 > </a>
        </div>
        <div class="cont">
            {% autoescape off %}
                {{ description }}...
            {% endautoescape %}
        </div>
    </div>

{% endblock %}


</body>
</html>

apps/organizations/templates/organizations/teacher-detail.html
<!DOCTYPE html>
<html>

{% extends 'base.html' %}
{% load static %}

<head>

    <!-- 页面标题每个页面需自定义 -->
    {% block html_title %}<title>教师详情 - 点点在线网</title>{% endblock %}

    <!--网页自定义的外联js-->
    {% block custom_head_js %}
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
    {% endblock %}

    <!--网页自定义的js-->
    {% block html_owner_js %}

        <script type="text/javascript">
            //收藏分享
            function add_fav(current_elem, fav_id, fav_type) {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'organizations:add_collection' %}",
                    data: {'fav_id': fav_id, 'fav_type': fav_type},
                    async: true,
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                        if (data.status === 'fail') {
                            if (data.msg === '用户未登录') {
                                window.location.href = "login.html";
                            } else {
                                alert(data.msg)
                            }
                        } else if (data.status === 'success') {
                            current_elem.text(data.msg)
                        }
                    },
                });
            }

            $(document).ready(function () {
                $('#jsLeftBtn').on('click', function () {
                    add_fav($(this), {{ teacher.id }}, 3);
                });
            });
            $(document).ready(function () {
                $('#jsRightBtn').on('click', function () {
                    add_fav($(this), {{ teacher.organization.id }}, 2);
                });
            });
        </script>

    {% endblock %}



</head>
<body>

<!-- 自定义面包屑导航 -->
{% block custom_breadcrumbs %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>教师详情</li>
            </ul>
        </div>
    </section>
{% endblock %}



<!-- 每个网页的页面主体，需自定义 -->
{% block custom_body %}
    <section>
        <div class="wp butler-detail-box butler-diaryd-box clearfix">
            <div class="fl list">
                <div class="butler_detail_list clearfix">
                    <div class="brief">
                        <dl class="des">
                            <dt>
                                <div class="picpic">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.teacher_image }}"/>
                                </div>
                                <div class="btn">
                                        <span class="fl btn1 collectionbtn" id="jsLeftBtn">
                                             {% if is_teacher_collected == '收藏' %}
                                                 收藏
                                             {% else %}
                                                 已收藏
                                             {% endif %}
                                        </span>
                                    <span class="fr btn2 shareBtn bdsharebuttonbox"
                                          data-text="授课教师-李老师-慕学网"
                                          data-desc="我在#慕课网#发现了"
                                          data-comment="李老师，工作年限：5年；学历：本科；所在公司：阿里巴巴&nbsp;；经典案例：django入门和深入；flask入门"
                                          data-url="/diary/hk_detail/10/">
                                            <span class="fl">分享</span>
                                            <a href="#" class="bds_more" data-cmd="more"></a>
                                        </span>
                                </div>
                            </dt>
                            <dd>
                                <a href="{% url 'organizations:teacher_detail' teacher.id %}">
                                    <h1>{{ teacher.teacher_name }}<span class="key picbig">金牌讲师</span></h1>
                                </a>
                                <ul class="cont">
                                    <li>工作年限：<span>{{ teacher.work_year }}</span></li>
                                    <li>就职公司：<span>{{ teacher.inauguration_company }}</span></li>
                                    <li>工作职位：<span>{{ teacher.company_position }}</span></li>
                                    <li>
                                        教学特点：
                                        <span>
                                            {% autoescape off %}
                                                {{ teacher.description }}
                                            {% endautoescape %}
                                        </span>
                                    </li>
                                </ul>
                            </dd>
                        </dl>
                    </div>
                </div>
                <div class="butler_detail_cont clearfix">
                    <div class="left layout">
                        <div class="head">
                            <ul class="tab_header">
                                <li class="{% if sort == '' %}active{% endif %}"><a href="?sort=">全部课程</a></li>
                                <li class="{% if sort == 'hot' %}active{% endif %}"><a href="?sort=hot">热门课程</a></li>
                            </ul>
                        </div>
                        <div class="companycenter">
                            <div class="group_list brief">

                                {% for course in courses.object_list %}
                                    <div class="module1_5 box">
                                    <a href="{% url 'courses:course_detail' course.id %}">
                                        <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.course_image }}"/>
                                    </a>
                                    <div class="des">
                                        <a href="{% url 'courses:course_detail' course.id %}">
                                            <h2>{{ course.course_name }}</h2>
                                        </a>
                                        <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                        <span class="fr">学习人数：{{ course.student_number }}</span>
                                    </div>
                                    <div class="bottom">
                                        <span class="fl">{{ course.course_teacher.organization }}</span>
                                        <span class="star fr  notlogin" data-favid="15">0</span>
                                    </div>
                                </div>
                                {% endfor %}

                            </div>
                        </div>
                        <div class="pageturn">
                            <ul class="pagelist">
                                {% if courses.has_previous %}
                                <li class="long">
                                    <a href="?{{ courses.previous_page_number.querystring }}">上一页</a>
                                </li>
                                {# 如果没有前一页，则不显示上一页字样#}
                            {% endif %}
                            {% for page in courses.pages %}
                                {% if page %}
                                    {% ifequal page courses.number %}
                                        <li class="active">{{ page }}</li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                {# 如果页面没有分页，则不显示任何内容#}
                                    <li class="none"><a href="" class="page">...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if courses.has_next %}
                                <li class="long"><a href="?{{ courses.next_page_number.querystring }}">下一页</a></li>
                                {# 如果没有下一页，则不显示下一页字样#}
                            {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="fr list">
                <div class="butler_detail_list">
                    <div class="right butler-company-box">
                        <div class="head">
                            <h1>授课机构</h1>
                            <p>知名高校，权威教学</p>
                        </div>
                        <div class="pic">
                            <a href="{% url 'organizations:organization_detail_homepage' teacher.organization.id %}">
                                <img width="150" height="80" src="{{ MEDIA_URL }}{{ teacher.organization.organization_image }}"/>
                            </a>
                        </div>
                        <a href="{% url 'organizations:organization_detail_homepage' teacher.organization.id %}">
                            <h2 class="center">{{ teacher.organization }}</h2>
                        </a>
                        <p class="center tell">地址：{{ teacher.organization.city }}</p>
                        <a class="btn" id="jsRightBtn">
                            {% if is_organization_collected == '收藏' %}
                                收藏
                             {% else %}
                                 已收藏
                             {% endif %}
                        </a>
                    </div>
                </div>

                <div class="butler_detail_cont">
                    <div class="butler_list_box">
                        <div class="right layout">
                            <div class="head">讲师排行榜</div>

                                {% for hot_teacher in hot_teachers %}
                                    <dl class="des">
                                        <span class="num fl">{% cycle '1' '2' '3' %}</span>
                                        <a href="{% url 'organizations:teacher_detail' hot_teacher.id %}">
                                            <dt>
                                                <img width="50" height="50" class="scrollLoading" src="{{ MEDIA_URL }}{{ hot_teacher.teacher_image }}"/>
                                            </dt>
                                        </a>
                                        <dd>
                                            <a href="{% url 'organizations:teacher_detail' hot_teacher.id %}">
                                                <h1>{{ hot_teacher.teacher_name }}</h1>
                                            </a>
                                            <p>工作年限：<span>{{ hot_teacher.work_year }}</span> 年</p>
                                        </dd>
                                    </dl>
                                {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}


</body>
</html>